# Generated by Django 5.2.5 on 2025-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talenthub_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('not_assigned', 'Not Assigned'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='not_assigned', max_length=20),
        ),
    ]
